src/Acme.BookStore.Web/Areas/Home/Components/CategoryViewComponent.cs
using Acme.BookStore.Authors;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Acme.BookStore.Web.Areas.Home.Components
{
    [ViewComponent(Name = "Category")]
    public class CategoryViewComponent: ViewComponent
    {
        private readonly EfCoreAuthorRepository _authorRepository;
        public CategoryViewComponent(EfCoreAuthorRepository authorRepository)
        {
            _authorRepository = authorRepository;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories = await _authorRepository.GetListAsync();
            return View("Index",categories);
        }
    }
}

src/Acme.BookStore.Web/Areas/Home/Components/SearchViewComponent.cs
using Acme.BookStore.Authors;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Acme.BookStore.Web.Areas.Home.Components
{
    [ViewComponent(Name = "Search")]
    public class SearchViewComponent : ViewComponent
    {
        private readonly EfCoreAuthorRepository _authorRepository;
        public SearchViewComponent(EfCoreAuthorRepository authorRepository)
        {
            _authorRepository = authorRepository;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories = await _authorRepository.GetListAsync();
            return View("Index",categories);
        } 
    }
}

src/Acme.BookStore.Web/Areas/Home/Components/SlideShowViewComponent.cs
using Acme.BookStore.Slides;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Acme.BookStore.Web.Areas.Home.Components
{
    [ViewComponent(Name = "SlideShow")]
    public class SlideShowViewComponent : ViewComponent
    {
        private readonly EfCoreSlideRepository _slideRepository;
        public SlideShowViewComponent(EfCoreSlideRepository slideRepository)
        {
            _slideRepository = slideRepository;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var slideshow = await _slideRepository.GetListAsync();
            return View("Index", slideshow);
        }
    }
}

src/Acme.BookStore.Web/Views/Shared/_UserLayout.cshtml
@*@using System.Security.Claims
@{
    var user = User.FindFirst(ClaimTypes.Name);
}*@

<!DOCTYPE HTML>
<head>
    <title>[Mới 100% Full Box] DoMinhTam Website</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="~/User/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/User/css/slider.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/User/css/paging.css" rel="stylesheet" type="text/css" media="all" />
    <link rel="shortcut icon" href="~/User/images/CV.jpg">
    <script type="text/javascript" src="~/User/js/jquery-1.7.2.min.js"></script>
    <script type="text/javascript" src="~/User/js/move-top.js"></script>
    <script type="text/javascript" src="~/User/js/easing.js"></script>
    <script type="text/javascript" src="~/User/js/startstop-slider.js"></script>
</head>
<html>
<body>
    <div class="wrap">
        <div class="header">
            <div class="headertop_desc">
                <div class="call">
                    <p><span>Need help?</span> call us <span class="number">1-22-3456789</span></p>
                </div>
                <div class="account_desc">
                    <ul>
                        <li><a href="#">Register</a></li>
                        <li><a href="#">Delivery</a></li>
                        <li><a href="#">Checkout</a></li>
                        @*@if (user != null)
                        {
                            <li><a asp-controller="customer" asp-action="profile">@user.Value</a></li>
                            <li><a asp-controller="customer" asp-action="signout">Logout</a></li>
                        }
                        else
                        {
                            <li><a asp-controller="customer" asp-action="login">Login</a></li>
                            <li><a href="#">My Account</a></li>
                        }*@
                    </ul>
                </div>
                <div class="clear"></div>
            </div>
            <div class="header_top">
                <div class="logo">
                    <a href="https://localhost:44374/home/public"><img src="~/User/images/logo.png" alt="" /></a>
                </div>
                <div class="cart">
            <p>
                Welcome to our Online Store! <span>Cart:</span><div id="dd" class="wrapper-dropdown-2">
                    0 item(s) - $0.00
                    <ul class="dropdown">
                        <li>you have no items in your Shopping cart</li>
                    </ul>
                </div>
            </p>
        </div>
                <script type="text/javascript">
                    function DropDown(el) {
                        this.dd = el;
                        this.initEvents();
                    }
                    DropDown.prototype = {
                        initEvents: function () {
                            var obj = this;

                            obj.dd.on('click', function (event) {
                                $(this).toggleClass('active');
                                event.stopPropagation();
                            });
                        }
                    }

                    $(function () {

                        var dd = new DropDown($('#dd'));

                        $(document).click(function () {
                            // all dropdowns
                            $('.wrapper-dropdown-2').removeClass('active');
                        });

                    });

                </script>
                <div class="clear"></div>
            </div>
            <div class="header_bottom">
                <div class="menu">
                    <ul>
                        <li class="active"><a href="https://localhost:44374/home/public">Home</a></li>
                        <li><a href="#">About</a></li>
                        <li><a href="#">Delivery</a></li>
                        <li><a href="#">News</a></li>
                        <li><a href="#">Contact</a></li>
                        <div class="clear"></div>
                    </ul>
                </div>
                <div class="search_box">
                    <form>
                        <input type="text" value="SEARCH" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'SEARCH';}"><input type="submit" value="">
                    </form>
                </div>
                @await Component.InvokeAsync("Search")
                <div class="clear"></div>
            </div>
            <div class="header_slide">
                @await Component.InvokeAsync("Category")

                @await Component.InvokeAsync("SlideShow")

                <div class="clear"></div>
            </div>
        </div>
        <div class="main">
            @RenderBody()
        </div>
    </div>
    <div class="footer">
        <div class="wrap">
            <div class="section group">
                <div class="col_1_of_4 span_1_of_4">
                    <h4>Information</h4>
                    <ul>
                        <li><a href="about.html">About Us</a></li>
                        <li><a href="contact.html">Customer Service</a></li>
                        <li><a href="#">Advanced Search</a></li>
                        <li><a href="delivery.html">Orders and Returns</a></li>
                        <li><a href="contact.html">Contact Us</a></li>
                    </ul>
                </div>
                <div class="col_1_of_4 span_1_of_4">
                    <h4>Why buy from us</h4>
                    <ul>
                        <li><a href="about.html">About Us</a></li>
                        <li><a href="contact.html">Customer Service</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                        <li><a href="contact.html">Site Map</a></li>
                        <li><a href="#">Search Terms</a></li>
                    </ul>
                </div>
                <div class="col_1_of_4 span_1_of_4">
                    <h4>My account</h4>
                    <ul>
                        <li><a href="contact.html">Sign In</a></li>
                        <li><a href="index.html">View Cart</a></li>
                        <li><a href="#">My Wishlist</a></li>
                        <li><a href="#">Track My Order</a></li>
                        <li><a href="contact.html">Help</a></li>
                    </ul>
                </div>
                <div class="col_1_of_4 span_1_of_4">
                    <h4>Contact</h4>
                    <ul>
                        <li><span>+91-123-456789</span></li>
                        <li><span>+00-123-000000</span></li>
                    </ul>
                    <div class="social-icons">
                        <h4>Follow Us</h4>
                        <ul>
                            <li><a href="#" target="_blank"><img src="~/User/images/facebook.png" alt="" /></a></li>
                            <li><a href="#" target="_blank"><img src="~/User/images/twitter.png" alt="" /></a></li>
                            <li><a href="#" target="_blank"><img src="~/User/images/skype.png" alt="" /> </a></li>
                            <li><a href="#" target="_blank"> <img src="~/User/images/dribbble.png" alt="" /></a></li>
                            <li><a href="#" target="_blank"> <img src="~/User/images/linkedin.png" alt="" /></a></li>
                            <div class="clear"></div>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="copy_right">
            <p><i class="fas fa-trademark"></i> 2020 MyBlock. | Redesign by <a href="https://tam1103.github.io/" target="_blank">Dominhtam1103@gmail.com</a></p>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function () {
            $().UItoTop({ easingType: 'easeOutQuart' });
        });
    </script>
    <a href="#" id="toTop"><span id="toTopHover"> </span></a>
</body>
</html>